pr: none
trigger: none

variables:
  - group: OlasInternational_RN # Cambia esto al nombre que hayas configurado

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true
    clean: true
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '20.x' # or specify '20.18.0'
  - script: corepack enable
    displayName: Corepack enable for yarn versions
  - script: |
      npm install -g eas-cli
      yarn install
    displayName: 'Install dependencies'
  - task: JavaToolInstaller@1
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Configurar Java 17'
  # Construcción del APK
  - script: |
      eas build --platform android --local --output=./build/app.aab
    displayName: 'Build app locally'
    env: 
      EXPO_TOKEN: $(EAS_TOKEN)

  # Publicar APK como artefacto
  - task: PublishBuildArtifacts@1
    inputs: 
      pathToPublish: 'build/app.aab'
      artifactName: 'android-app'
    displayName: "Publish artifact"
